Update Website Styles!!!
socialjusticehackathon/website pull request #29
Opened 2024-03-24 02:14 UTC by travissouthard

# Overview

Updates the styles and content to fit Jamie's design (linked in #28)

Closes #28 

# Demo

Before
<img width="1280" alt="image" src="https://github.com/socialjusticehackathon/website/assets/64238570/7fd39254-a831-4bf0-9e23-2053beb42211">

After
<img width="1280" alt="image" src="https://github.com/socialjusticehackathon/website/assets/64238570/69cf5d85-bad4-4b15-ab27-f19408b83529">

# Testing

- Either locally or with the "view deployment" feature, look through the pages and ensure:
  - [ ] The content is all correct
  - [ ] The site is readable
  - [ ] The designs fit [Jamie's designs](https://www.figma.com/file/0dnG0Wk1kBGnprclGlpQrl/Social-Justice-Hackathon-Design-Edits?type=design&node-id=13-10952&mode=design&t=ej812faEhm58lUoj-0) (There are a couple things we can't adjust as granularly since Quarto is a little odd)

2024-03-24 03:15 UTC, insiyahj commented
Requests for PR 29: 
Please see edits on the screenshots attached + updated text for under the large graphic:
Students, programmers, “civic-minded hackers”, faculty, justice advocates, public servants, community legal providers, writers, story-tellers, and members of the Philly community will all come together to design creative solutions to respond to specific justice needs of residents and neighborhoods most impacted by social, economic, and environmental injustices in Philadelphia. This event is free to attend, and open to all participants, regardless of coding experience or affiliation with an organization or university. See you soon!

![image](https://github.com/socialjusticehackathon/website/assets/157067324/69467a3a-52f2-4ae5-bd1a-987182c9052e)

![image](https://github.com/socialjusticehackathon/website/assets/157067324/fd20c213-cb36-4b75-98af-03ad84f751fc)

2024-03-24 18:27 UTC, machow requested changes
This is looking great! I added suggestions for CSS to ensure...

* banner text wraps on wide displays
* footer links aren't side-by-side on narrow displays (which made their link text wrap).

Feel free to punt on / adapt the suggestions!

edit: Insiyah flagged the text visibility in the hero banner, which seems important. I've added a black outline to the text in my CSS suggestions. I'd suggest we merge with less than ideal visibility, so someone can take that specific issue head on.

2024-03-24 18:27 UTC, machow commented on styles.scss
> +
It looks like on narrow screens, the footer link text does some aggressive wrapping.

<img width="585" alt="image" src="https://github.com/socialjusticehackathon/website/assets/2574498/625a745c-0bbe-4a9d-b2b2-5670ad44203c">

I was able to---for narrow displays---get the links to each be on their own line, using this rough css:

```suggestion

@media (max-width: 720px) {
    .nav-footer-left {
      flex: none !important;

      .footer-items {
        display: block !important;
      }
    }

}

```

2024-03-24 18:27 UTC, machow commented on styles.scss
> +
On wide displays, the headers aren't each on a newline. "Philly's 2nd" and Social Justice Hackathon are put side-by-side.

<img width="1701" alt="image" src="https://github.com/socialjusticehackathon/website/assets/2574498/3e623d44-5076-4101-90a2-ed612cc6ffa0">

The suggested CSS below ensures it wraps on wide displays

```suggestion
  display: flex;
  /* Uncomment below to vertically center text */
  /*justify-content: center;*/
  align-items: center;
  flex-direction: column;
  /* outline letters in black */
  /* from https://stackoverflow.com/a/4772914 */
  text-shadow: 1px 0px 0 #000, 0 -1px 0 #000, 0 1px 0 #000, -1px 0 0 #000;

```

Here is the result:

<img width="1702" alt="image" src="https://github.com/socialjusticehackathon/website/assets/2574498/a4db92ab-5720-4c17-b227-2d78ff822a44">

2024-03-24 18:27 UTC, machow commented on styles.scss
> +
Note that text-shadow is a little bit funky for anything other than 1 px outline. There's the `-website-text-stroke` property that's pretty widely supported, but I haven't tried that.

2024-03-24 18:27 UTC, machow commented on index.qmd
> +  The Philadelphia Social Justice Hackathon will be held at the Drexel Law School from April 5-7, 2024, to bring students, programmers, and other “civic-minded hackers” together – to work in collabor
From [this slack thread](https://codeforphilly.slack.com/archives/C06DXBH1HE2/p1711299903315159?thread_ts=1711248924.227479&cid=C06DXBH1HE2)

```suggestion
Students, programmers, “civic-minded hackers”, faculty, justice advocates, public servants, community legal providers, writers, story-tellers, and members of the Philly community will all come together to design creative solutions to respond to specific justice needs of residents and neighborhoods most impacted by social, economic, and environmental injustices in Philadelphia.
```

2024-03-26 03:38 UTC, travissouthard commented
Merging for times' sake but all notes here and in the [website slack channel](https://codeforphilly.slack.com/archives/C06DXBH1HE2). Any further changes should be noted in new issues.

2024-03-26 03:38 UTC, merged