add blogpost for 2022 recap
socialjusticehackathon/website pull request #3
Opened 2024-01-18 21:07 UTC by ha0ye

2024-01-19 01:25 UTC, machow commented
In case it's useful, I think this extension lets you embed tweets 

https://github.com/sellorm/quarto-social-embeds

2024-01-25 20:34 UTC, machow commented
@travissouthard if this looks good to you, WDYT of us merging it, and then we can always tweak the post before the site goes live.

2024-01-26 14:05 UTC, travissouthard requested changes
Hi @ha0ye! This looks great thank you for putting in this work!
There are two organizational notes below that I think will help our future selves out and make it clear to future collaborators how to interact with the project.
Would you also be able to delete the sample post as part of this PR? I think that would be distracting otherwise.
![image](https://github.com/socialjusticehackathon/website/assets/64238570/bbb27b12-6407-4285-b2db-8d804beb0252)

Once those changes are in, I think yes to @machow on merging it now and having it be ready when we launch.

2024-01-26 14:05 UTC, travissouthard commented on posts/sponsors.png
I think it would be helpful to have any images we use for the blog to go into an `assets` or `images` folder within the `posts` folder so that the posts stand alone

2024-01-26 14:05 UTC, travissouthard commented on posts/recap-2022.qmd
The post itself is well put together and nicely formatted! I think it will be helpful to add a `01` to the start of the file name to help us keep the posts organized for ourselves

2024-01-27 22:34 UTC, ha0ye commented
Suggestions sound good to me, away for the weekend, suggest yyyy-mm-dd-title naming format for posts.

2024-01-27 23:37 UTC, travissouthard commented
> Suggestions sound good to me, away for the weekend, suggest yyyy-mm-dd-title naming format for posts.

I love the date idea!

2024-01-29 17:44 UTC, ha0ye commented on posts/recap-2022.qmd
done in 5eebf11

2024-01-31 02:50 UTC, travissouthard approved these changes
Thanks for making those changes!

2024-02-01 01:55 UTC, merged